Module2 task1
htmlacademy-adaptive/1543995-cat-energy-28 pull request #2
Opened 2023-04-02 16:04 UTC by s-mikki

2023-04-03 20:09 UTC, DKukushkin91 requested changes

2023-04-03 20:09 UTC, DKukushkin91 commented on Readme.md
> -* Наставник: [Дмитрий Кукушкин](https://up.htmlacademy.ru/adaptive/28/user/599015).
Тут всё было ок, ничего менять не нужно

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +<div class="body__container">
Этот div не нужен.

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +                    <button class="navigation__button">
button не должен оборачивать ссылки. Просто сделай её отдельно

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +                        <div class="buttons">
это не кнопки, это навигационный список ссылок

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +                            <a class="buttons__link" href="#">Главная</a>
navigation__link

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +                <h3 class="header__title">Занялся собой? Займись котом!</h3>
тэг `<p>`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +        <section class="section">
используй [миксы ](https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%B8%D0%BA%D1%81) 

Например:

    <section class="section hero">

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +            <div class="section__header">
`class='hero__header"` и т.д в этой секции

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +            <a class="button" href="#">Подобрать программу</a>
Тут секция hero заканчивается

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +            <div class="section__container">
Это новая секция catalog-preview

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +                <div class="block">
тут идёт список элементов, `catalog-preview__list --> catalog-preview__item` и т.д

название `block` слишком абстрактно, не понятно что за блок, что содержит.

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +        <section class="section__main">
секции в целом по сайту одинаковые, используй для них `class='section about-product'` и миксуй с другим блоком

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +            <div class="inner">
Всегда используй идентичный неминг в классах, т.е не очень хорошо использовать container, inner, box, wrapper и т.д, пользуйся каким-то 1 названием для оберток в проекте. 

Конкретно тут это был бы `'about-product__container'`

НО эту обертка вообще  не нужена

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +                <h2 class="inner__title">Как это работает</h2>
Класс нужно будет сменить под родительский блок

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +            <div class="example">
это новая секция `class='section example'`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +                <h3 class="example__heading">Затраты на питание: 15 000 РУБ.</h3>
просто тег `<p>`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +        <div class="contacts">
`contacts` не относится к футеру, это нужно перенести в  `section` в `main` вместе с картой, это всё контакты

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +            <p class="contacts__text">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
раздели в теге `<p>`  текст на

     <span>ул. Большая Конюшенная, д. 19/8</span>
     <span>Санкт-Петербург</span>

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +        <nav class="footer__navigation">
это не навигация, навигация обычно ведёт по сайту, тут же списки ссылок на внешние ресурсы.

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +                <svg class="social__icon"></svg>
Оберни иконки в тег `<a>` так же не забудь о атрибуте `target='_blank'`  
[Почитай](https://doka.guide/html/a/#atributy) о атрибутах тега `a`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/index.html
> +            <div class="footer__links">
это не просто ссылки, так же не забудь о атрибутах для внешних ресурсов

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +    <header class="header">
см комиты к index.html касательно header и других общих элементов

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +       <section class="promo">
Тут нет промоакций. 
Смотри на общий смысл в секции, это анкета, но в целом этот класс не нужен
`class='section'` тут достаточно

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                   <h3 class="form__title">Заполните анкету, и мы подберем программу питания для вашего кота</h3>
тег `<p>` class `'form_subtitle'`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +               <div class="form__container">
`class='form__title-container'`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                   <h1 class="form__heading">Подбор программы</h1>
Называй всё одинаково. Не должно быть 10 штук разных заголовков (title, heading, caption и т.д.)

Проще всего называй все заголовки `какой-то блок__title`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +               <div class="form__content">
Это лишняя обертка, у нас же филдсет и так оборачивает блок

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                                   <label class="form__label" for="name">Имя:*</label>
Так использовать лэйблы можно, но не совсем удобно (нужно заботиться о id постоянно у инпута),

Лучше делай так:

    <label>
        <span>text:</span>
        <input>
    </label>

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                               <div class="form__date">
если label будет оборачивать input, этот див не нужен

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +               <div class="form__container">
не нужен, есть филдсет

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                               <label class="label__wrap" for="hotel">
hotel? O_o если копируешь, проверяй, что ты используешь. for и id если оборачиваем labelom не нужен

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                                   <span class="control__radio"></span>похудение
из `span` сбежал текст

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                                   Набор массы
из span сбежал текст

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                                   <input class="visually__hidden input__radio" type="radio" id="motel" name="Жильё" value="массы">
motel? O_o если копируешь, проверяй, что ты используешь. for и id если оборачиваем labelom не нужен

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                                   Не знаю (Нужен ваш совет)
всё тоже самое что и выше

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                       <fieldset class="radio">
`form__fieldset` если нужна специфичность для бордеров задай модификатор `form_fieldset--border`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                               <label class="label__wrap" for="hotel">
Инпуты с label вообще без БЭМ, [почитай ](https://ru.bem.info/methodology/quick-start/) о нём

Если использовать это в разрезе отдельного компонента, дак назови всё одинаково.

    <label class='custom-radio'>
        <input class='custom-radio__input'>
        <span  class='custom-radio__text'>text</span>
    </label>

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                   <fieldset class="contacts">
`class='form__fieldset form-contacts'`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                       <div class="form__date">
см рекомендации выше

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +               <fieldset class="comment">
`class='form__fieldset form-comments'`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +               <fieldset class="checkbox">
`class='form__fieldset form-extra'`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +                   <input class="visually__hidden input__radio" type="checkbox" id="sugar" name="Жильё" value="похудение" checked="">
см выше, сделай по аналогии с `custom-radio`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +               <button class="button" type="submit"></button>
Где текст в кнопке?

2023-04-03 20:09 UTC, DKukushkin91 commented on source/form.html
> +    <footer class="footer">
см комментарии к странице index.html

2023-04-03 20:09 UTC, DKukushkin91 commented on source/catalog.html
> +<div class="body__container">
см комментарии к странице index.html

2023-04-03 20:09 UTC, DKukushkin91 commented on source/catalog.html
> +        <h1 class="heading"></h1>
Отсутствует заголовок. heading чего? Это всё таки заголовок секции `catalog`, назови его `catalog__title` и перемести в секцию, добавь текст с макета

2023-04-03 20:09 UTC, DKukushkin91 commented on source/catalog.html
> +            <div class="catalog__container">
Это не нумерованный список из товаров, используй `ul` `li` вместо дивов

2023-04-03 20:09 UTC, DKukushkin91 commented on source/catalog.html
> +                    <div class="catalog__titles">
это не заголовки. 

Структура у карточки должна быть такая. 


      <li>
          <img>
          <div>
              <p>Заголовок</p>
              <dl>
                <dt>Масса</dt>
                <dd>500 г</dd>
              </dl>
          </div>
          <a>Текст</a>
      </li>

2023-04-03 20:09 UTC, DKukushkin91 commented on source/catalog.html
> +                    <div class="catalog__titles">
И пересмотри нейминг классов. Это `catalog__list -> catalog__item -> catalog__item-img` и т.д

2023-04-03 20:09 UTC, DKukushkin91 commented on source/catalog.html
> +            <div class="catalog__container">
Это всё так же элемент списка каталога с префиксом --more

2023-04-03 20:09 UTC, DKukushkin91 commented on source/catalog.html
> +            <h2 class="additionally__heading">Дополнительные товары</h2>
`additionally__title` нейминг должен быть един

2023-04-03 20:09 UTC, DKukushkin91 commented on source/catalog.html
> +            <div class="additionally__wrap">
Это список дополнительных товаров. `ul -> li`

2023-04-03 20:09 UTC, DKukushkin91 commented on source/catalog.html
> +                <h3 class="additionally__title">питьевая вода</h3>
Это всё не заголовки. Можно обернуть в `strong` но не в h3

2023-04-03 20:09 UTC, DKukushkin91 commented on source/catalog.html
> +            <div class="additionally__container">
Отдельная секция, promotion

2023-04-03 20:09 UTC, DKukushkin91 commented on source/catalog.html
> +    <footer class="footer">
см комиты к index.html

2023-04-04 03:42 UTC, s-mikki commented on source/index.html
> +<div class="body__container">
+

2023-04-04 03:46 UTC, s-mikki commented on Readme.md
> -* Наставник: [Дмитрий Кукушкин](https://up.htmlacademy.ru/adaptive/28/user/599015).
+

2023-04-04 03:49 UTC, s-mikki commented on source/index.html
> +                        <div class="buttons">
+

2023-04-04 03:49 UTC, s-mikki commented on source/index.html
> +                            <a class="buttons__link" href="#">Главная</a>
+

2023-04-04 03:50 UTC, s-mikki commented on source/index.html
> +                <h3 class="header__title">Занялся собой? Займись котом!</h3>
+

2023-04-04 03:51 UTC, s-mikki commented on source/index.html
> +        <section class="section">
+

2023-04-04 03:53 UTC, s-mikki commented on source/index.html
> +            <div class="section__header">
+

2023-04-04 03:53 UTC, s-mikki commented on source/index.html
> +            <a class="button" href="#">Подобрать программу</a>
+

2023-04-04 03:57 UTC, s-mikki commented on source/index.html
> +            <div class="section__container">
+

2023-04-04 03:57 UTC, s-mikki commented on source/index.html
> +                <div class="block">
+

2023-04-04 03:59 UTC, s-mikki commented on source/index.html
> +            <div class="inner">
+

2023-04-04 04:00 UTC, s-mikki commented on source/index.html
> +                <h2 class="inner__title">Как это работает</h2>
+

2023-04-04 04:00 UTC, s-mikki commented on source/index.html
> +            <div class="example">
+

2023-04-04 04:01 UTC, s-mikki commented on source/index.html
> +                <h3 class="example__heading">Затраты на питание: 15 000 РУБ.</h3>
+

2023-04-04 04:09 UTC, s-mikki commented on source/index.html
> +            <p class="contacts__text">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
+

2023-04-04 04:11 UTC, s-mikki commented on source/index.html
> +        <div class="contacts">
+

2023-04-04 05:46 UTC, s-mikki commented on source/index.html
> +        <nav class="footer__navigation">
+

2023-04-04 05:46 UTC, s-mikki commented on source/index.html
> +                <svg class="social__icon"></svg>
+

2023-04-04 05:49 UTC, s-mikki commented on source/index.html
> +            <div class="footer__links">
+

2023-04-04 05:51 UTC, s-mikki commented on source/form.html
> +    <header class="header">
+

2023-04-04 05:51 UTC, s-mikki commented on source/form.html
> +       <section class="promo">
+

2023-04-04 05:52 UTC, s-mikki commented on source/form.html
> +                   <h3 class="form__title">Заполните анкету, и мы подберем программу питания для вашего кота</h3>
+

2023-04-04 05:52 UTC, s-mikki commented on source/form.html
> +               <div class="form__container">
+

2023-04-04 05:54 UTC, s-mikki commented on source/form.html
> +                   <h1 class="form__heading">Подбор программы</h1>
+

2023-04-04 05:55 UTC, s-mikki commented on source/form.html
> +               <div class="form__content">
+

2023-04-04 12:42 UTC, s-mikki commented on source/form.html
> +                               <div class="form__date">
+

2023-04-04 12:42 UTC, s-mikki commented on source/form.html
> +                                   <label class="form__label" for="name">Имя:*</label>
+

2023-04-04 12:58 UTC, s-mikki commented on source/form.html
> +                               <label class="label__wrap" for="hotel">
+

2023-04-04 12:59 UTC, s-mikki commented on source/form.html
> +                                   <span class="control__radio"></span>похудение
+

2023-04-04 12:59 UTC, s-mikki commented on source/form.html
> +                                   <input class="visually__hidden input__radio" type="radio" id="motel" name="Жильё" value="массы">
+

2023-04-04 12:59 UTC, s-mikki commented on source/form.html
> +                                   Не знаю (Нужен ваш совет)
+

2023-04-04 13:22 UTC, s-mikki commented on source/form.html
> +                               <label class="label__wrap" for="hotel">
+

2023-04-04 13:24 UTC, s-mikki commented on source/form.html
> +                                   Набор массы
+

2023-04-04 13:38 UTC, s-mikki commented on source/form.html
> +                   <fieldset class="contacts">
+

2023-04-04 13:40 UTC, s-mikki commented on source/form.html
> +                       <div class="form__date">
+

2023-04-04 13:41 UTC, s-mikki commented on source/form.html
> +               <fieldset class="comment">
+

2023-04-04 13:42 UTC, s-mikki commented on source/form.html
> +               <fieldset class="checkbox">
+

2023-04-04 13:42 UTC, s-mikki commented on source/form.html
> +                   <input class="visually__hidden input__radio" type="checkbox" id="sugar" name="Жильё" value="похудение" checked="">
+

2023-04-04 13:43 UTC, s-mikki commented on source/form.html
> +               <button class="button" type="submit"></button>
+

2023-04-04 13:43 UTC, s-mikki commented on source/form.html
> +    <footer class="footer">
+

2023-04-04 13:43 UTC, s-mikki commented on source/catalog.html
> +<div class="body__container">
+

2023-04-04 13:45 UTC, s-mikki commented on source/catalog.html
> +        <h1 class="heading"></h1>
+

2023-04-04 14:12 UTC, s-mikki commented on source/catalog.html
> +                    <div class="catalog__titles">
+

2023-04-04 14:12 UTC, s-mikki commented on source/catalog.html
> +            <div class="catalog__container">
+

2023-04-04 14:17 UTC, s-mikki commented on source/catalog.html
> +            <h2 class="additionally__heading">Дополнительные товары</h2>
+

2023-04-04 14:44 UTC, s-mikki commented on source/catalog.html
> +    <footer class="footer">
+

2023-04-04 14:44 UTC, s-mikki commented on source/catalog.html
> +            <div class="additionally__container">
+

2023-04-04 14:45 UTC, s-mikki commented on source/catalog.html
> +                <h3 class="additionally__title">питьевая вода</h3>
+

2023-04-04 17:34 UTC, DKukushkin91 approved these changes

2023-04-04 18:02 UTC, s-mikki commented on source/index.html
> +                    <button class="navigation__button">
+

2023-04-05 14:56 UTC, DKukushkin91 requested changes

2023-04-05 14:56 UTC, DKukushkin91 commented on source/catalog.html
> +        <ul class="product">
это `catalog__list`

2023-04-05 14:56 UTC, DKukushkin91 commented on source/catalog.html
> +            <li class="product__list">
это `catalog__item` 

list это список всегда, а item элемент списка

 внутри тоже поправь на `catalog__твой елемент`

2023-04-05 14:56 UTC, DKukushkin91 commented on source/catalog.html
> +                    <dl class="product-price">
`dl` это `description list` т.е список с описанием, он не состоит из 1 условно пункта, все описание положи в 1 `dl`

2023-04-05 14:56 UTC, DKukushkin91 commented on source/catalog.html
> +                <dl class="additional-price">
это просто `div` с 2 `span` внутри, тут списка особо и нет

2023-04-05 14:56 UTC, DKukushkin91 commented on source/index.html
> +        <img class="hero__img" src="#" width="" height="" alt="#">
Пустые атрибуты ширины и высоты нужно убрать, т.к если пока не знаем что вводить, не нужно их добавлять, что бы не ловить ошибок [валидатора](https://validator.w3.org/nu/#textarea)

2023-04-05 15:10 UTC, s-mikki commented on source/catalog.html
> +        <ul class="product">
+

2023-04-05 15:10 UTC, s-mikki commented on source/catalog.html
> +            <li class="product__list">
+

2023-04-05 15:10 UTC, s-mikki commented on source/catalog.html
> +                    <dl class="product-price">
+

2023-04-05 15:11 UTC, s-mikki commented on source/catalog.html
> +                <dl class="additional-price">
+

2023-04-05 15:12 UTC, s-mikki commented on source/index.html
> +        <img class="hero__img" src="#" width="" height="" alt="#">
+

2023-04-05 15:36 UTC, merged